/*!
 * Undo applied Prisma migrations (down migrations)
 *
 * I'm Queue Software Project
 * Copyright (C) 2025  imqueue.com <support@imqueue.com>
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 *
 * If you want to use this code in a closed source (commercial) project, you can
 * purchase a proprietary commercial license. Please contact us at
 * <support@imqueue.com> to get commercial licensing options.
 */

/**
 * Undo applied Prisma migrations — Prisma has no native "down". Each migration
 * folder may hold a hand-written `down.sql` (authoritative); when absent, one is
 * generated by diffing the migration set with vs. without the target (via a
 * throwaway shadow database) and written to the folder for review. Rolling back
 * runs the `down.sql` and removes the migration's `_prisma_migrations` record
 * (and optionally the folder), so the schema can move backwards one step.
 *
 * `migrateDown()` is the reusable core: it takes everything as parameters (the
 * database URL, paths, a progress reporter) and touches no globals — ready to
 * lift into a shared library. The CLI at the bottom is the only part that reads
 * `process.argv` / writes to the console, and runs only when invoked directly.
 *
 * CLI usage:
 *   node --import tsx prisma/migrate-down.ts --database-url <url> [options]
 *     --database-url <url>   Postgres connection string (required)
 *     --steps N             roll back the N most recent applied migrations (default 1)
 *     --generate-only       only (re)generate missing down.sql files; don't apply
 *     --delete-folder       also delete the migration folder after rollback
 *     --dry-run             show what would happen; make no changes
 */

import { execFileSync } from 'node:child_process';
import {
    cpSync,
    existsSync,
    mkdtempSync,
    readdirSync,
    readFileSync,
    rmSync,
    writeFileSync,
} from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { pathToFileURL } from 'node:url';
import pg from 'pg';

const LOCK = 'migration_lock.toml';

export interface MigrateDownOptions {
    /** Postgres connection string for the database to roll back. */
    databaseUrl: string;
    /** Absolute path to the Prisma migrations directory. */
    migrationsDir: string;
    /** Working directory for `prisma migrate diff` (holds prisma.config.ts). */
    projectRoot: string;
    /** Number of most-recent applied migrations to roll back (default 1). */
    steps?: number;
    /** Only (re)generate missing `down.sql` files; don't apply anything. */
    generateOnly?: boolean;
    /** Delete the migration folder after a successful rollback. */
    deleteFolder?: boolean;
    /** Report the actions without changing anything. */
    dryRun?: boolean;
    /** Progress reporter (defaults to a no-op — the core stays silent). */
    log?: (message: string) => void;
}

export interface MigrateDownResult {
    /** Migration names processed, newest first. */
    processed: string[];
}

/** Resolved, non-optional config shared by the internal helpers. */
interface Context {
    databaseUrl: string;
    migrationsDir: string;
    projectRoot: string;
    log: (message: string) => void;
}

/** Migration folder names (timestamp-prefixed), oldest → newest. */
function migrationDirs(migrationsDir: string): string[] {
    return readdirSync(migrationsDir, { withFileTypes: true })
        .filter(entry => entry.isDirectory() && /^\d+_/.test(entry.name))
        .map(entry => entry.name)
        .sort();
}

/** Applied, not-rolled-back migrations from `_prisma_migrations`, newest first. */
async function appliedMigrations(client: pg.Client): Promise<string[]> {
    const { rows } = await client.query<{ migration_name: string }>(
        `SELECT migration_name FROM "_prisma_migrations"
          WHERE finished_at IS NOT NULL AND rolled_back_at IS NULL
          ORDER BY started_at DESC`,
    );

    return rows.map(row => row.migration_name);
}

/** Copy the given migrations (+ lock file) into a fresh temp dir; return its path. */
function tempMigrations(migrationsDir: string, names: string[]): string {
    const dir = mkdtempSync(join(tmpdir(), 'ze-migrate-down-'));
    cpSync(join(migrationsDir, LOCK), join(dir, LOCK));
    for (const name of names) {
        cpSync(join(migrationsDir, name), join(dir, name), { recursive: true });
    }

    return dir;
}

/** A throwaway shadow-database URL derived from `base` (same server, new db). */
function shadowDatabaseUrl(base: string): { url: string; name: string } {
    const url = new URL(base);
    const name = `ze_migrate_down_shadow_${Date.now()}`;
    url.pathname = `/${name}`;

    return { url: url.toString(), name };
}

async function withShadowDatabase<T>(
    databaseUrl: string,
    fn: (shadowUrl: string) => Promise<T>,
): Promise<T> {
    const admin = new URL(databaseUrl);
    admin.pathname = '/postgres';
    const { url, name } = shadowDatabaseUrl(databaseUrl);

    const client = new pg.Client({ connectionString: admin.toString() });
    await client.connect();
    await client.query(`DROP DATABASE IF EXISTS "${name}"`);
    await client.query(`CREATE DATABASE "${name}"`);
    try {
        return await fn(url);
    } finally {
        await client.query(`DROP DATABASE IF EXISTS "${name}" WITH (FORCE)`);
        await client.end();
    }
}

/**
 * Generate the down SQL for `target`: the diff that takes the schema from the
 * state INCLUDING `target` back to the state WITHOUT it. Uses a shadow database
 * because migration-set diffs replay migrations.
 */
async function generateDown(ctx: Context, target: string): Promise<string> {
    const all = migrationDirs(ctx.migrationsDir);
    const withoutTarget = all.filter(name => name < target);
    const fromDir = tempMigrations(
        ctx.migrationsDir,
        all.filter(name => name <= target),
    );
    const toDir = withoutTarget.length
        ? tempMigrations(ctx.migrationsDir, withoutTarget)
        : null;
    // "to" is the state without the target: an earlier migration set, or empty
    // if the target is the first migration.
    const toArgs = toDir ? ['--to-migrations', toDir] : ['--to-empty'];

    try {
        return await withShadowDatabase(ctx.databaseUrl, shadowUrl =>
            Promise.resolve(
                execFileSync(
                    'npx',
                    [
                        'prisma',
                        'migrate',
                        'diff',
                        '--from-migrations',
                        fromDir,
                        ...toArgs,
                        '--script',
                    ],
                    {
                        cwd: ctx.projectRoot,
                        encoding: 'utf8',
                        // Read by prisma.config.ts as datasource.shadowDatabaseUrl.
                        env: { ...process.env, SHADOW_DATABASE_URL: shadowUrl },
                    },
                ),
            ),
        );
    } finally {
        rmSync(fromDir, { recursive: true, force: true });
        if (toDir) {
            rmSync(toDir, { recursive: true, force: true });
        }
    }
}

/** Read a folder's `down.sql`, generating and persisting it first if missing. */
async function resolveDown(ctx: Context, target: string): Promise<string> {
    const downPath = join(ctx.migrationsDir, target, 'down.sql');
    if (existsSync(downPath)) {
        return readFileSync(downPath, 'utf8');
    }

    ctx.log(`  generating ${target}/down.sql …`);
    const sql = await generateDown(ctx, target);
    writeFileSync(downPath, sql);
    ctx.log(`  wrote ${downPath} — review it before trusting the rollback`);

    return sql;
}

interface RollbackFlags {
    generateOnly: boolean;
    deleteFolder: boolean;
    dryRun: boolean;
}

async function rollbackOne(
    ctx: Context,
    client: pg.Client,
    target: string,
    flags: RollbackFlags,
): Promise<void> {
    const downSql = await resolveDown(ctx, target);
    if (flags.generateOnly) {
        return;
    }
    if (flags.dryRun) {
        ctx.log(
            `  [dry-run] would apply down.sql and drop record for ${target}`,
        );

        return;
    }

    await client.query('BEGIN');
    try {
        await client.query(downSql);
        await client.query(
            `DELETE FROM "_prisma_migrations" WHERE migration_name = $1`,
            [target],
        );
        await client.query('COMMIT');
    } catch (err) {
        await client.query('ROLLBACK');
        throw err;
    }

    if (flags.deleteFolder) {
        rmSync(join(ctx.migrationsDir, target), {
            recursive: true,
            force: true,
        });
    }
    ctx.log(`  rolled back ${target}`);
}

/**
 * Roll back the N most-recent applied migrations. Pure of globals — every input
 * (database URL, paths, reporter) is supplied by the caller.
 */
export async function migrateDown(
    options: MigrateDownOptions,
): Promise<MigrateDownResult> {
    const ctx: Context = {
        databaseUrl: options.databaseUrl,
        migrationsDir: options.migrationsDir,
        projectRoot: options.projectRoot,
        log: options.log ?? (() => {}),
    };
    const flags: RollbackFlags = {
        generateOnly: options.generateOnly ?? false,
        deleteFolder: options.deleteFolder ?? false,
        dryRun: options.dryRun ?? false,
    };
    const steps = options.steps ?? 1;
    if (!Number.isInteger(steps) || steps < 1) {
        throw new Error('steps must be a positive integer');
    }

    const client = new pg.Client({ connectionString: ctx.databaseUrl });
    await client.connect();
    try {
        const applied = await appliedMigrations(client);
        const targets = applied.slice(0, steps);
        if (targets.length === 0) {
            ctx.log('No applied migrations to roll back.');

            return { processed: [] };
        }

        ctx.log(
            `${flags.generateOnly ? 'Generating down.sql for' : 'Rolling back'} ${targets.length} migration(s):`,
        );
        // Newest first — each down assumes later migrations are already undone.
        for (const target of targets) {
            ctx.log(`- ${target}`);
            await rollbackOne(ctx, client, target, flags);
        }

        return { processed: targets };
    } finally {
        await client.end();
    }
}

/* eslint-disable no-console -- the CLI shim below reports progress to stdout */

interface CliArgs extends RollbackFlags {
    databaseUrl: string;
    steps: number;
}

const VALUE_FLAGS = new Set(['--steps', '--database-url']);

/** Fold the space-separated `--flag value` form into `--flag=value` so each
 * token can be parsed on its own. */
function normalizeArgs(argv: string[]): string[] {
    return argv.reduce<string[]>((tokens, token) => {
        const prev = tokens[tokens.length - 1];
        if (prev !== undefined && VALUE_FLAGS.has(prev)) {
            tokens[tokens.length - 1] = `${prev}=${token}`;

            return tokens;
        }
        tokens.push(token);

        return tokens;
    }, []);
}

function parseArgs(argv: string[]): CliArgs {
    const args: CliArgs = {
        databaseUrl: '',
        steps: 1,
        generateOnly: false,
        deleteFolder: false,
        dryRun: false,
    };
    for (const token of normalizeArgs(argv)) {
        if (token === '--generate-only') {
            args.generateOnly = true;
            continue;
        }
        if (token === '--delete-folder') {
            args.deleteFolder = true;
            continue;
        }
        if (token === '--dry-run') {
            args.dryRun = true;
            continue;
        }
        if (token.startsWith('--steps=')) {
            args.steps = Number(token.slice('--steps='.length));
            continue;
        }
        if (token.startsWith('--database-url=')) {
            args.databaseUrl = token.slice('--database-url='.length);
            continue;
        }
        throw new Error(`Unknown argument: ${token}`);
    }
    if (!args.databaseUrl) {
        throw new Error('--database-url <url> is required');
    }

    return args;
}

async function cli(): Promise<void> {
    const { databaseUrl, steps, generateOnly, deleteFolder, dryRun } =
        parseArgs(process.argv.slice(2));

    await migrateDown({
        databaseUrl,
        steps,
        generateOnly,
        deleteFolder,
        dryRun,
        migrationsDir: join(
            import.meta.dirname,
            '..',
            '..',
            'prisma',
            'migrations',
        ),
        projectRoot: join(import.meta.dirname, '..', '..'),
        log: message => console.log(message),
    });
}

// Run the CLI only when this file is executed directly, so importing the module
// (as a library, or from a test) has no side effects.
if (
    process.argv[1] &&
    import.meta.url === pathToFileURL(process.argv[1]).href
) {
    await cli();
}
